from room import Room

dock=Room("dock")
water1=Room("water")
water2=Room("water")
water3=Room("water")
hall=Room("big hall")
entryway=Room("tall entryway")
stairs=Room("long stairs")
bedroom=Room("bedroom")
famlyroom=Room("family room")
dungeon=Room("dungeon")
aviary=Room("aviary")

dock.set_description("dock","A long wooden dock covered in moss.")
water1.set_description("ocean","A blue ocean.")
water2.set_description("ocean","Ablue ocean.")
water3.set_description("water","A blue ocean.")
hall.set_description("big hall","A big long hall.")
entryway.set_description("wonderfull entryway", "This entryway is good. You don't want to leave it.")
stairs.set_description("pair of steep stair","Theese stairs are great! They are made of fancey oak.")
bedroom.set_description("normal bedroom", "This is an ordinary bedroom. It has white walls and a bed.")
famlyroom.set_description("nice family room", "This is a nice family room with a couch.")
dungeon.set_description("dungeon","This is a scary dungeon like the ones from movies. You are scared.")
aviary.set_description("aviary", "This is a beutiful and large aviary. You see many birds and poles for them to perch on.")

dock.add_exit('east', water1.id)
dock.add_exit('west', water2.id)
dock.add_exit('north', water3.id)
